DROP VIEW "I806258"."TEMP_HUM_READINGS";

CREATE VIEW "I806258"."TEMP_HUM_READINGS" AS
 SELECT T.c_value AS tvalue, H.c_value AS hvalue, T.c_timestamp as timestamp FROM
(SELECT c_sensor,c_timestamp,c_value
FROM "I806258"."T_IOT_47D5A5E41FE370C9079F"
WHERE c_sensor = 'temperature') AS T
JOIN
(SELECT c_sensor,c_timestamp,c_value
FROM "I806258"."T_IOT_47D5A5E41FE370C9079F"
WHERE c_sensor = 'humidity') AS H
ON T.C_TIMESTAMP = H.C_TIMESTAMP;

DROP VIEW "I806258"."TEMP_HUM_READINGS_IN_NUMS";

CREATE VIEW "I806258"."TEMP_HUM_READINGS_IN_NUMS" AS
SELECT T.c_value AS tvalue, H.c_value AS hvalue, T.c_timestamp as TS FROM
(SELECT c_sensor,c_timestamp,c_value
FROM "I806258"."T_IOT_47D5A5E41FE370C9079F"
WHERE c_sensor = 'temperature') AS T
JOIN
(SELECT c_sensor,c_timestamp,c_value
FROM "I806258"."T_IOT_47D5A5E41FE370C9079F"
WHERE c_sensor = 'humidity') AS H
ON T.C_TIMESTAMP = H.C_TIMESTAMP;

DROP FUNCTION "I806258"."SENSOR_VALUES_SINCE_HOURS";

CREATE FUNCTION "I806258"."SENSOR_VALUES_SINCE_HOURS" (sinceHours INT)
RETURNS TABLE (TEMP_VALUE DOUBLE, HUM_VALUE DOUBLE, TS TIMESTAMP)
LANGUAGE SQLSCRIPT
AS
  timeNowInSeconds INT;
  timeNowInSeconds1 INT;
  sinceSeconds INT;
BEGIN
  timeNowInSeconds1 := SECONDS_BETWEEN(TO_TIMESTAMP('1970-01-01 00:00:00'),NOW());
  timeNowInSeconds := SECONDS_BETWEEN(TO_TIMESTAMP('1970-01-01 00:00:00'),TO_TIMESTAMP('2016-03-25 19:57:00'));
  sinceSeconds := :sinceHours * 3600;
  RETURN
  SELECT TO_DOUBLE(TVALUE) AS TEMP_VALUE,
         TO_DOUBLE(HVALUE) AS HUM_VALUE,
         ADD_SECONDS(TO_DATE('1970-01-01 00:00:00'),TIMESTAMP) as TS
  FROM "I806258"."TEMP_HUM_READINGS"
  WHERE TVALUE != 'nan' AND HVALUE != 'nan'
        AND TIMESTAMP > (:timeNowInSeconds - :sinceSeconds);
END;

-- sensor values by hourly averages query

    SELECT AVG(TEMP_VALUE) AS TVALUE, AVG(HUM_VALUE) AS HVALUE, HOUR FROM
    (SELECT TEMP_VALUE,HUM_VALUE,HOUR(TS) AS HOUR
    FROM "I806258"."SENSOR_VALUES_SINCE_HOURS"(23) ORDER BY TS)
    GROUP BY HOUR;
    
-- sensor values by daily averages
SELECT AVG(TEMP_VALUE) AS TVALUE,    AVG(HUM_VALUE) AS HVALUE ,YEAR,MONTH,DAY
FROM 
    (SELECT TEMP_VALUE,HUM_VALUE,YEAR(TS) AS YEAR,MONTH(TS) AS MONTH, DAYOFMONTH(TS) AS DAY
    FROM I806258.TEMP_HUM_READINGS_IN_NUMS)
    GROUP BY YEAR,MONTH,DAY

